# Generated by Django 5.1.6 on 2025-02-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_players',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='min_players',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('FY MCA', 'First Year MCA'), ('SY MCA', 'Second Year MCA'), ('FY MBA', 'First Year MBA'), ('SY MBA', 'Second Year MBA')], max_length=10)),
                ('players', models.JSONField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
