# Generated by Django 5.1.6 on 2025-03-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rule_book',
            field=models.FileField(blank=True, null=True, upload_to='rule_books/'),
        ),
    ]
