# Generated by Django 5.1.6 on 2025-04-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
