# Generated by Django 5.1.6 on 2025-04-01 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventregistration_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactFormModel',
        ),
    ]
