# Generated by Django 5.1.6 on 2025-04-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_contactformmodel_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='subject',
            field=models.CharField(choices=[('General inquiry', 'General inquiry'), ('Technical support', 'Technical support'), ('Feedback & Suggestion', 'Feedback & Suggestion'), ('Lost & found', 'Lost & found')], default='General inquiry', max_length=50),
        ),
    ]
