# Generated by Django 5.1.6 on 2025-04-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_volunteer_requirement_volunteerregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerregistration',
            name='department',
            field=models.CharField(choices=[('FY MCA', 'First Year MCA'), ('SY MCA', 'Second Year MCA'), ('FY MBA', 'First Year MBA'), ('SY MBA', 'Second Year MBA')], default='FY MCA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerregistration',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerregistration',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerregistration',
            name='rollnumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
