# Generated by Django 5.1.6 on 2025-04-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_volunteerregistration_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
