# Generated by Django 5.1.6 on 2025-04-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
